name: ai_recipe_app
description: "Chef AI Recipe app with AI fetures."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Note: Adjusted for compatibility with recent packages

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.7
  http: ^1.2.1 # Note: Updated to a more recent compatible version
  flutter_dotenv: ^6.0.0 # Note: Updated to a more recent compatible version
  firebase_core: ^4.0.0 # Note: Updated versions for Firebase
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  shimmer: ^3.0.0
  flutter_markdown: ^0.7.1
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  pdf: ^3.10.8
  printing: ^5.12.0 # Note: Updated to a more recent compatible version
  path_provider: ^2.1.3
  share_plus: ^11.1.0 # Note: Updated to a more recent compatible version
  provider: ^6.1.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  intl: ^0.20.2 # Note: Updated to a more recent compatible version
  permission_handler: ^12.0.1
  open_file: ^3.3.2 # Note: Updated to a more recent compatible version
  file_saver: ^0.3.1 # Note: Updated to a more recent compatible version
  firebase_storage: ^13.0.0
  cloudinary_public: ^0.23.1
  cached_network_image: ^3.3.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.2
  googleapis: ^14.0.0 # Note: Updated to a more recent compatible version
  googleapis_auth: ^2.0.0
  path: ^1.9.0
  flutter_animate: ^4.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # ✅ ADDED flutter_launcher_icons HERE
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/food_search.json
    - assets/options.json
    - assets/cooking.json
    - assets/images/logo.png
    - assets/images/chef.png
    - assets/images/cooking.png
    - assets/images/frying-pan.png
    - assets/images/tray.png

# ✅ ADDED THIS ENTIRE SECTION AT THE END
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"